{% set name = "netreg" %}
{% set version = "1.11.3" %}
{% set sha256 = "8a7e768677335559feccd8224b2f3a5396bc79332120de08e4bf41f4989289f7" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  sha256: {{ sha256 }}
  url: https://github.com/dirmeier/netReg/archive/v{{ version }}.tar.gz

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - boost-cpp
    - armadillo >=7.800.1
    - openblas >=0.2.19
    - zlib
    - hdf5
  run:
    - boost-cpp
    - armadillo >=7.800.1
    - openblas >=0.2.19
    - zlib
    - hdf5

test:
  commands:
    - netReg -h

about:
  home: https://github.com/dirmeier/netReg
  license: GPL3
  summary: "netReg fits linear regression models using network-penalization."
  license_file: LICENSE
  doc_url: https://dirmeier.github.io/netReg/
