{% set name = "parasail-python" %}
{% set version = "1.1.20" %}
{% set sha256 = "ba17914197de443a005784ec91df49a246da8c9397c4fe73395555d25553cede" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/jeffdaily/parasail-python/archive/v{{ version }}.tar.gz
  sha256: "{{ sha256 }}"
  patches:
    - darwin-libtool-name.patch

build:
  number: 0

requirements:
  host:
    - python
    - setuptools
    - zlib
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - m4
    - autoconf
    - automake
    - libtool
  run:
    - python
    - numpy

test:
  imports:
    - parasail

about:
  home: https://github.com/jeffdaily/parasail-python
  license: BSD
  license_family: BSD
  summary: pairwise sequence alignment library

