{% set version = '0.5.0.9000' %}

package:
  name: r-liger
  version: {{ version }}

source:
  url: https://github.com/MacoskoLab/liger/archive/v{{ version }}.tar.gz
  sha256: 987a76ebdd8b3f179284a796922f3c18cfed08a1d5415ac9079581ce6de21979

build:
  number: 0
  script: R CMD INSTALL --build .
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - r-base
    - r-fnn
    - r-hmisc
    - r-matrix
    - r-rann.l1
    - r-rcpp >=0.12.10
    - r-rcpparmadillo
    - r-rtsne
    - r-cowplot
    - r-dosnow
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-ica
    - r-irlba
    - r-mclust
    - r-patchwork
    - r-plyr
    - r-riverplot
    - r-snow
    - r-rccpeigen
    - r-psych
    - r-rann

  run:
    - r-base
    - r-fnn
    - r-hmisc
    - r-matrix
    - r-rann.l1
    - r-rcpp >=0.12.10
    - r-rcpparmadillo
    - r-rtsne
    - r-cowplot
    - r-dosnow
    - r-dplyr
    - r-foreach
    - r-ggplot2
    - r-ggrepel
    - r-ica
    - r-irlba
    - r-mclust
    - r-patchwork
    - r-plyr
    - r-riverplot
    - r-snow
    - r-rccpeigen
    - r-psych
    - r-rann
    - openjdk >=6
    - umap-learn

test:
  commands:
    - $R -e "library('liger')"

about:
  home: https://github.com/MacoskoLab/liger
  license: GPL-3
  summary: R package for integrating and analyzing multiple single-cell datasets
  license_family: GPL3
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raivivek
