{% set version = "2.4.0" %}

package:
  name: bowtie2
  version: {{ version }}

source:
  url: https://github.com/BenLangmead/bowtie2/archive/v{{ version }}.tar.gz
  sha256: 161909662de2d07952ee5962fbeccf509b1063eaeb900515c3ad0412668543ab

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - zlib
    - tbb-devel
    - tbb
  run:
    - python
    - perl
    - zlib
    - tbb

test:
  commands:
    - bowtie2 --help
    - bowtie2-align-l --help
    - bowtie2-align-s --help
    - bowtie2-build --help
    - bowtie2-build-l --help
    - bowtie2-build-s --help
    - bowtie2-inspect --help
    - bowtie2-inspect-l --help
    - bowtie2-inspect-s --help

about:
  home: 'http://bowtie-bio.sourceforge.net/bowtie2/index.shtml'
  license: GPLv3
  license_file: LICENSE
  summary: Fast and sensitive read alignment

extra:
  identifiers:
    - biotools:bowtie2
    - doi:10.1038/nmeth.1923
    - debian:bowtie2
